env:
  global:
  - CC_TEST_REPORTER_ID=630b5c89960e7c989c7b87ed61b915066646bf63f89390efd785a0fb3b9a55b4
language: node_js
rvm:
  - 2.2.0
node_js:
  - 'node'
  - '8'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
